version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: araculturedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@araculture.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - 5050:80

  backend:
    build: ./ara-culture-backend
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/araculturedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres_password

  frontend:
    build: ./ara-culture-frontend
    ports:
      - 3000:80
    depends_on:
      - backend

volumes:
  pgdata:
