apiVersion: apps/v1
kind: Deployment
metadata:
  name: ara-frontend
  labels:
    app: ara-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ara-frontend
  template:
    metadata:
      labels:
        app: ara-frontend
    spec:
      containers:
        - name: ara-frontend
          image: vexced17/ara_culture_frontend:latest
          ports:
            - containerPort: 80
          env:
            # URL interna del backend
            - name: REACT_APP_API_URL
              value: http://ara-backend:8080
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20