apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ara-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: araculture.example.com   # Resuelto en /etc/hosts → 192.168.58.2
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ara-frontend
                port:
                  number: 80
