name: Frontend CI/CD

on:
  push:
    branches:
      - main


env:
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  IMAGE_NAME: ara_culture_frontend
  IMAGE_TAG: ${{ github.sha }}
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --watchAll=false

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=ara-culture-frontend
            -Dsonar.organization=tu-org
            -Dsonar.host.url=$SONAR_HOST_URL
            -Dsonar.login=$SONAR_TOKEN

      - name: Snyk Scan
        uses: snyk/actions@0.4.0
        with:
          command: test
          args: --all-projects
        env:
            SNYK_TOKEN: SNYK_TOKEN  
  docker:
    needs: build-test
    runs-on: ubuntu-latest
    if: needs.build-test.result == 'success'

    steps:
      - name: Checkout frontend
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image frontend
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image frontend
        run: docker push $IMAGE_NAME:$IMAGE_TAG
