name: Frontend CI/CD

on:
  push:
    branches:
      - main


env:
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  IMAGE_NAME: vexced17/ara_culture_frontend
  IMAGE_TAG: ${{ github.sha }}
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test || echo "No tests found, skipping"
      - name: Lint
        run:  npm run lint || echo "Lint warnings/errors ignored"

      - name: Build
        run: npm run build

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=Ara-culture-frontend
            -Dsonar.organization=vexced
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  snyk-scan:
    runs-on: ubuntu-latest
    needs: build-test

    steps:      
    
      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Scan
        run: snyk test --all-projects --fail-on=all
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  docker:
    needs: [build-test, snyk-scan]
    runs-on: ubuntu-latest
    if: needs.snyk-scan.result == 'success'

    steps:
      - name: Checkout frontend
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image frontend
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image frontend
        run: docker push $IMAGE_NAME:$IMAGE_TAG
