name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --watchAll=false

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=ara-culture-frontend
            -Dsonar.organization=tu-org
            -Dsonar.host.url=$SONAR_HOST_URL
            -Dsonar.login=$SONAR_TOKEN

      - name: Snyk Scan
        uses: snyk/actions@0.4.0
        with:
          command: test
          args: --all-projects
        env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
